### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by TyrionChou** [look4pritam/tfmtcnn#5]
hi，look4pritam
    when i run 3.Generate a hard dataset i.e. RNet dataset, i got a problem as follows.

Generating landmark samples.
( 1000 / 10000 ) number of input images are done.
( 2000 / 10000 ) number of input images are done.
( 3000 / 10000 ) number of input images are done.
( 4000 / 10000 ) number of input images are done.
( 5000 / 10000 ) number of input images are done.
( 6000 / 10000 ) number of input images are done.
( 7000 / 10000 ) number of input images are done.
( 8000 / 10000 ) number of input images are done.
( 9000 / 10000 ) number of input images are done.
( 10000 / 10000 ) number of input images are done.
Generated landmark samples.
Generating image samples.
Traceback (most recent call last):
  File "generate_hard_dataset.py", line 99, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "generate_hard_dataset.py", line 91, in main
    status = hard_dataset.generate(args.annotation_image_dir, args.annotation_file_name, args.landmark_image_dir, args.landmark_file_name, args.train_root_dir, args.target_root_dir)
  File "/root/tfmtcnn/tfmtcnn-master/datasets/HardDataset.py", line 135, in generate
    if(not self._generate_image_samples(annotation_file_name, annotation_image_dir, model_train_dir, image_size, target_root_dir)):
  File "/root/tfmtcnn/tfmtcnn-master/datasets/HardDataset.py", line 47, in _generate_image_samples
    return(wider_dataset.generate_samples(annotation_image_dir, annotation_file_name, model_train_dir, self.network_name(), minimum_face, target_root_dir))
  File "/root/tfmtcnn/tfmtcnn-master/datasets/HardFaceDataset.py", line 142, in generate_samples
    face_detector = FaceDetector(model_train_dir)
  File "/root/tfmtcnn/tfmtcnn-master/nets/FaceDetector.py", line 56, in __init__
    status_ok = self._rnet.setup_inference_network(rnet_model_path) and status_ok
  File "/root/tfmtcnn/tfmtcnn-master/nets/RNet.py", line 108, in setup_inference_network
    return(self.load_model(self._session, checkpoint_path))
  File "/root/tfmtcnn/tfmtcnn-master/nets/AbstractFaceDetector.py", line 70, in load_model
    saver.restore(session, self._model_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./data/models/mtcnn/train/RNet
	 [[Node: save/RestoreV2_8 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_8/tensor_names, save/RestoreV2_8/shape_and_slices)]]
	 [[Node: save/RestoreV2_5/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_72_save/RestoreV2_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2_8', defined at:
  File "generate_hard_dataset.py", line 99, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "generate_hard_dataset.py", line 91, in main
    status = hard_dataset.generate(args.annotation_image_dir, args.annotation_file_name, args.landmark_image_dir, args.landmark_file_name, args.train_root_dir, args.target_root_dir)
  File "/root/tfmtcnn/tfmtcnn-master/datasets/HardDataset.py", line 135, in generate
    if(not self._generate_image_samples(annotation_file_name, annotation_image_dir, model_train_dir, image_size, target_root_dir)):
  File "/root/tfmtcnn/tfmtcnn-master/datasets/HardDataset.py", line 47, in _generate_image_samples
    return(wider_dataset.generate_samples(annotation_image_dir, annotation_file_name, model_train_dir, self.network_name(), minimum_face, target_root_dir))
  File "/root/tfmtcnn/tfmtcnn-master/datasets/HardFaceDataset.py", line 142, in generate_samples
    face_detector = FaceDetector(model_train_dir)
  File "/root/tfmtcnn/tfmtcnn-master/nets/FaceDetector.py", line 56, in __init__
    status_ok = self._rnet.setup_inference_network(rnet_model_path) and status_ok
  File "/root/tfmtcnn/tfmtcnn-master/nets/RNet.py", line 108, in setup_inference_network
    return(self.load_model(self._session, checkpoint_path))
  File "/root/tfmtcnn/tfmtcnn-master/nets/AbstractFaceDetector.py", line 69, in load_model
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./data/models/mtcnn/train/RNet
	 [[Node: save/RestoreV2_8 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_8/tensor_names, save/RestoreV2_8/shape_and_slices)]]
	 [[Node: save/RestoreV2_5/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_72_save/RestoreV2_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

I just run the process 1,2,3, I wonder if run order is wrong?

**Comment by look4pritam** [comment]
Please check CelebA branch, which contains latest code. Follow readme file.
And let me know.
